// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89ImXbiKosw6eTCC8S1_vY8BzGq_SFY0',
    appId: '1:1064417466216:web:039565a60d9b0b74db28dd',
    messagingSenderId: '1064417466216',
    projectId: 'withcenter-test-5',
    authDomain: 'withcenter-test-5.firebaseapp.com',
    storageBucket: 'withcenter-test-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzaVr0SDNvkdTeDLYMnjd6ms9YMNZ1xw',
    appId: '1:1064417466216:android:c393e11d98cb73dfdb28dd',
    messagingSenderId: '1064417466216',
    projectId: 'withcenter-test-5',
    storageBucket: 'withcenter-test-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRwPbyMBfsr7MgBaR2Mv7FBg1PuxsnBo',
    appId: '1:1064417466216:ios:0d1fc24161640b1ddb28dd',
    messagingSenderId: '1064417466216',
    projectId: 'withcenter-test-5',
    storageBucket: 'withcenter-test-5.appspot.com',
    iosBundleId: 'com.modelhouse.example',
  );
}
